config/routes.rb
VchatManage::Application.routes.draw do

  get "operators/index"

  devise_for :operators

  namespace :admin do
    resources :operators do
      member do
        get "delete"
        get "block"
        get "unblock"
        get "profile"
        get "permission"
        get "session_history"
        get "attendance_history"
        get "attendance_by_date/:date", :action=>"attendance_history", :as=>"attendance_by_date"
      end
      get :autocomplete_skill_name, :on => :collection
      get :message_history, :on => :collection
    end
    resources :pictures do
      member do
        get "delete"
      end
    end
    resources :schedules do
      member do
        get "delete"
      end
      collection do
        get "work_page"
        get "rota_index"
        get "rota_slot/:date/:number", :action=>"rota_slot",:as=>"rota_slot"
        get "cancel/:schedule", :action=>"cancel", :as=>"cancel"
        get "index_by_date/:date", :action=>"index", :as=>"index_by_date"
        get "rindex_by_date/:date", :action=>"rota_index", :as=>"rindex_by_date"
        post "add_operator"
        post "request_holidays"
        post "note"
      end
    end
    resources :skills do
      member do
        get "delete"
      end
    end
    resources :topics do
      member do
        get "delete"
      end
    end
    resources :systemmetas do
      member do
        get "delete"
      end
      get :permission, :on => :collection
      get :market, :on => :collection
      post :marketing, :on => :collection
      post :updates, :on => :collection
    end
    resources :messages do
      member do
        post "read"
      end
      collection do
        get "t/:topic"=>"messages#topic",:as=>"t"
        get "sent"
      end
    end
    resources :users do
      member do
        get "delete"
        get "block"
        get "unblock"
      end
    end
    resources :chat_messages do
      collection do
        get "get_chat_users"
      end
    end 
    resources :permissions
    resources :reminders
    match '/statistics' => 'pages#general'
    match '/statistics/leaderboard' => 'pages#leaderboard'
    match '/statistics/online_ops' => 'pages#online_ops'
    match '/statistics/message_history' => 'pages#message_history'
    match '/statistics/payment_for_ops' => 'pages#payment_for_ops'
    match '/statistics/notes_history' => 'pages#notes_history'
  end
  match "api/login" => 'webservise#login'
  match "api/register" => 'webservise#register'
  match "api/forgotpassword" => 'webservise#forgotpassword'
  match "api/getalloperators" => 'webservise#getalloperators'
  match "api/getrandomagent" => 'webservise#getrandomagent'
  match "api/getlastagent" => 'webservise#getlastagent'
  match "api/getfavoriteoperators" => 'webservise#getfavoriteoperators'
  match "api/getoperatorinfo" => 'webservise#getoperatorinfo'
  match "api/changepassword" => 'webservise#changepassword'
  match "api/changeavatar" => 'webservise#changeavatar'
  match "api/setusercredit" => 'webservise#setusercredit'
  match "api/setrate" => 'webservise#setrate'
  match "api/getrecentoperators" => 'webservise#getrecentoperators'
  match "api/favoriteoperator" => 'webservise#favoriteoperator'
  match "api/unfavoriteoperator" => 'webservise#unfavoriteoperator'
  match "api/getmessagelist" => 'webservise#getmessagelist'
  match "api/sendmessage" => 'webservise#sendmessage'
  match "api/sawdailymessage" => 'webservise#sawdailymessage'
  match "api/endsession" => 'webservise#endsession'
  match "api/getuserinfo" => 'webservise#getuserinfo'

  root :to => "admin/operators#index"

end

app/views/admin/pages/general.html.erb
<% content_for :menu do %>
  <ul class="maintabmenu multipletabmenu">
    <li class="current">
      <%= link_to "General", admin_statistics_path %>
    </li>
    <li>
      <%= link_to "Leaderboard", admin_statistics_leaderboard_path %>
    </li>
    <li>
      <%= link_to "Online Ops", admin_statistics_online_ops_path %>
    </li>
    <li>
      <%= link_to "Message History", admin_statistics_message_history_path %>
    </li>
    <li>
      <%= link_to "Payment for op", admin_statistics_payment_for_ops_path %>
    </li>
    <li>
      <%= link_to "Notes History", admin_statistics_notes_history_path %>
    </li>
  </ul>
<% end %>
<div>
  <div class="contenttitle radiusbottom0">
    <h2 class="help"><span>Reach</span></h2>
  </div>
  <!--contenttitle-->
  <table cellspacing="0" cellpadding="0" border="0" class="stdtable">
    <colgroup>
      <col class="con0">
      <col class="con1">
      <col class="con0">
      <col class="con1">
      <col class="con0">
    </colgroup>

    <tbody>
      <tr>
        <td>Total App Installs:</td>
        <td>289</td>
      </tr>
      <tr>
        <td>App Installs This Month:</td>
        <td>19</td>
      </tr>
    </tbody>
  </table><br>
</div>
<div>
  <div class="contenttitle radiusbottom0">
    <h2 class="help"><span>Sales</span></h2>
  </div>
  <!--contenttitle-->
  <table cellspacing="0" cellpadding="0" border="0" class="stdtable">
    <colgroup>
      <col class="con0">
      <col class="con1">
      <col class="con0">
      <col class="con1">
      <col class="con0">
    </colgroup>

    <tbody>
      <tr>
        <td>Total Sales:</td>
        <td>21</td>
      </tr>
      <tr>
        <td>Total Takings:</td>
        <td>21</td>
      </tr>
      <tr>
        <td>50 Credits:</td>
        <td>21</td>
      </tr>
      <tr>
        <td>250 Credits:</td>
        <td>21</td>
      </tr>
      <tr>
        <td>1000 Credits:</td>
        <td>21</td>
      </tr>
      <tr>
        <td>2500 Credits:</td>
        <td>21</td>
      </tr>
    </tbody>
  </table><br>
</div>

app/views/admin/pages/leaderboard.html.erb
<% content_for :menu do %>
  <ul class="maintabmenu multipletabmenu">
    <li>
      <%= link_to "General", admin_statistics_path %>
    </li>
    <li class="current">
      <%= link_to "Leaderboard", admin_statistics_leaderboard_path %>
    </li>
    <li>
      <%= link_to "Online Ops", admin_statistics_online_ops_path %>
    </li>
    <li>
      <%= link_to "Message History", admin_statistics_message_history_path %>
    </li>
    <li>
      <%= link_to "Payment for op", admin_statistics_payment_for_ops_path %>
    </li>
    <li>
      <%= link_to "Notes History", admin_statistics_notes_history_path %>
    </li>
  </ul>
<% end %>
<div class="contenttitle radiusbottom0">
  <h2 class="table"><span>Leaderboard</span></h2>
</div><!--contenttitle-->	
<table class="stdtable" border="0" cellpadding="0" cellspacing="0">
  <colgroup>
      <col class="con0">
      <col class="con1">
      <col class="con0">
      <col class="con1">
      <col class="con0">
  </colgroup>

  <thead>
    <tr>
      <th class="head0">No</th>
      <th class="head1">Login Number</th>
      <th class="head0">Op name</th>
      <th class="head1">Email Address</th>
      <th class="head0">Rating</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th class="head0">No</th>
      <th class="head1">Login Number</th>
      <th class="head0">Op name</th>
      <th class="head1">Email Address</th>
      <th class="head0">Rating</th>
    </tr>
  </tfoot>
  <tbody>
    <tr>
      <td>1</td>
      <td>qinghan910</td>
      <td>Qing Han</td>
      <td>qinghan910@hotmail.com</td>
      <td>8</td>
    </tr>
    <tr>
      <td>2</td>
      <td>jolst</td>
      <td>JO</td>
      <td>jolst@hotmail.com</td>
      <td>4</td>
    </tr>
    <% (1..10).each do  %>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    <% end %>
  </tbody>
</table>                

app/views/admin/pages/message_history.html.erb
<% content_for :menu do %>
  <ul class="maintabmenu multipletabmenu">
    <li>
      <%= link_to "General", admin_statistics_path %>
    </li>
    <li>
      <%= link_to "Leaderboard", admin_statistics_leaderboard_path %>
    </li>
    <li>
      <%= link_to "Online Ops", admin_statistics_online_ops_path %>
    </li>
    <li  class="current">
      <%= link_to "Message History", admin_statistics_message_history_path %>
    </li>
    <li>
      <%= link_to "Payment for op", admin_statistics_payment_for_ops_path %>
    </li>
    <li>
      <%= link_to "Notes History", admin_statistics_notes_history_path %>
    </li>
  </ul>
<% end %>
<div class="contenttitle radiusbottom0">
  <h2 class="table"><span>Leaderboard</span></h2>
</div><!--contenttitle-->	
<table class="stdtable" border="0" cellpadding="0" cellspacing="0">
  <colgroup>
      <col class="con0">
      <col class="con1">
      <col class="con0">
      <col class="con1">
      <col class="con0">
  </colgroup>

  <thead>
    <tr>
      <th class="head0">Date</th>
      <th class="head1">Sender</th>
      <th class="head0">To</th>
      <th class="head1">Message</th>
      <th class="head0">Picture</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th class="head0">Date</th>
      <th class="head1">Sender</th>
      <th class="head0">To</th>
      <th class="head1">Message</th>
      <th class="head0">Picture</th>
    </tr>
  </tfoot>
  <tbody>
    <tr>
      <td>04/08/2013 18:25:02</td>
      <td>Qing Han</td>
      <td>User 1</td>
      <td>Message content</td>
      <td>&nbsp;</td>
    </tr>
    <% (1..10).each do  %>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/pages/notes_history.html.erb
<% content_for :menu do %>
  <ul class="maintabmenu multipletabmenu">
    <li>
      <%= link_to "General", admin_statistics_path %>
    </li>
    <li>
      <%= link_to "Leaderboard", admin_statistics_leaderboard_path %>
    </li>
    <li>
      <%= link_to "Online Ops", admin_statistics_online_ops_path %>
    </li>
    <li>
      <%= link_to "Message History", admin_statistics_message_history_path %>
    </li>
    <li>
      <%= link_to "Payment for op", admin_statistics_payment_for_ops_path %>
    </li>
    <li class="current">
      <%= link_to "Notes History", admin_statistics_notes_history_path %>
    </li>
  </ul>
<% end %>
<div class="contenttitle radiusbottom0">
  <h2 class="table"><span>Leaderboard</span></h2>
</div><!--contenttitle-->	
<table class="stdtable" border="0" cellpadding="0" cellspacing="0">
  <colgroup>
      <col class="con0">
      <col class="con1">
      <col class="con0">
      <col class="con1">
      <col class="con0">
  </colgroup>

  <thead>
    <tr>
      <th class="head0">No</th>
      <th class="head1">Login Number</th>
      <th class="head0">Op name</th>
      <th class="head1">Email Address</th>
      <th class="head0">Rating</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th class="head0">No</th>
      <th class="head1">Login Number</th>
      <th class="head0">Op name</th>
      <th class="head1">Email Address</th>
      <th class="head0">Action</th>
    </tr>
  </tfoot>
  <tbody>
    <tr>
      <td>1</td>
      <td>qinghan910</td>
      <td>Qing Han</td>
      <td>qinghan910@hotmail.com</td>
      <td>Kick</td>
    </tr>
    <tr>
      <td>2</td>
      <td>jolst</td>
      <td>JO</td>
      <td>jolst@hotmail.com</td>
      <td>Kick</td>
    </tr>
    <% (1..10).each do  %>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/pages/online_ops.html.erb
<% content_for :menu do %>
  <ul class="maintabmenu multipletabmenu">
    <li>
      <%= link_to "General", admin_statistics_path %>
    </li>
    <li>
      <%= link_to "Leaderboard", admin_statistics_leaderboard_path %>
    </li>
    <li class="current">
      <%= link_to "Online Ops", admin_statistics_online_ops_path %>
    </li>
    <li>
      <%= link_to "Message History", admin_statistics_message_history_path %>
    </li>
    <li>
      <%= link_to "Payment for op", admin_statistics_payment_for_ops_path %>
    </li>
    <li>
      <%= link_to "Notes History", admin_statistics_notes_history_path %>
    </li>
  </ul>
<% end %>
<div class="contenttitle radiusbottom0">
  <h2 class="table"><span>Leaderboard</span></h2>
</div><!--contenttitle-->	
<table class="stdtable" border="0" cellpadding="0" cellspacing="0">
  <colgroup>
      <col class="con0">
      <col class="con1">
      <col class="con0">
      <col class="con1">
      <col class="con0">
  </colgroup>

  <thead>
    <tr>
      <th class="head0">No</th>
      <th class="head1">Login Number</th>
      <th class="head0">Op name</th>
      <th class="head1">Email Address</th>
      <th class="head0">Rating</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th class="head0">No</th>
      <th class="head1">Login Number</th>
      <th class="head0">Op name</th>
      <th class="head1">Email Address</th>
      <th class="head0">Action</th>
    </tr>
  </tfoot>
  <tbody>
    <tr>
      <td>1</td>
      <td>qinghan910</td>
      <td>Qing Han</td>
      <td>qinghan910@hotmail.com</td>
      <td>Kick</td>
    </tr>
    <tr>
      <td>2</td>
      <td>jolst</td>
      <td>JO</td>
      <td>jolst@hotmail.com</td>
      <td>Kick</td>
    </tr>
    <% (1..10).each do  %>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/pages/payment_for_ops.html.erb
<% content_for :menu do %>
  <ul class="maintabmenu multipletabmenu">
    <li>
      <%= link_to "General", admin_statistics_path %>
    </li>
    <li>
      <%= link_to "Leaderboard", admin_statistics_leaderboard_path %>
    </li>
    <li>
      <%= link_to "Online Ops", admin_statistics_online_ops_path %>
    </li>
    <li>
      <%= link_to "Message History", admin_statistics_message_history_path %>
    </li>
    <li class="current">
      <%= link_to "Payment for op", admin_statistics_payment_for_ops_path %>
    </li>
    <li>
      <%= link_to "Notes History", admin_statistics_notes_history_path %>
    </li>
  </ul>
<% end %>
<div class="contenttitle radiusbottom0">
  <h2 class="table"><span>Leaderboard</span></h2>
</div><!--contenttitle-->	
<table class="stdtable" border="0" cellpadding="0" cellspacing="0">
  <colgroup>
      <col class="con0">
      <col class="con1">
      <col class="con0">
      <col class="con1">
      <col class="con0">
  </colgroup>

  <thead>
    <tr>
      <th class="head0">Op</th>
      <th class="head1">Total Msg Sent</th>
      <th class="head0">Payscale</th>
      <th class="head1">Value</th>
      <th class="head0">Sub Total</th>
      <th class="head0">Total Due</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th class="head0">Op</th>
      <th class="head1">Total Msg Sent</th>
      <th class="head0">Payscale</th>
      <th class="head1">Value</th>
      <th class="head0">Sub Total</th>
      <th class="head0">Total Due</th>
    </tr>
  </tfoot>
  <tbody>
    <tr>
      <td>op1</td>
      <td>50</td>
      <td>10 * A</td>
      <td>10 * 0.05</td>
      <td>0.50p</td>
      <td>3.30p</td>
    </tr>
    <tr>
      <td>op2</td>
      <td>150</td>
      <td>100 * C</td>
      <td>40 * 0.07</td>
      <td>2.80p</td>
      <td>10.0p</td>
    </tr>
    <% (1..10).each do  %>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    <% end %>
  </tbody>
</table>