config/routes.rb
VchatManage::Application.routes.draw do

  get "operators/index"

  devise_for :operators

  namespace :admin do
    resources :operators do
      member do
        get "delete"
        get "block"
        get "unblock"
        get "profile"
        get "permission"
        get "session_history"
        get "attendance_history"
        get "attendance_by_date/:date", :action=>"attendance_history", :as=>"attendance_by_date"
      end
      get :autocomplete_skill_name, :on => :collection
      get :message_history, :on => :collection
    end
    resources :pictures do
      member do
        get "delete"
      end
    end
    resources :schedules do
      member do
        get "delete"
      end
      collection do
        get "work_page"
        get "rota_index"
        get "rota_slot/:date/:number", :action=>"rota_slot",:as=>"rota_slot"
        get "cancel/:schedule", :action=>"cancel", :as=>"cancel"
        get "index_by_date/:date", :action=>"index", :as=>"index_by_date"
        get "rindex_by_date/:date", :action=>"rota_index", :as=>"rindex_by_date"
        post "add_operator"
        post "request_holidays"
        post "note"
      end
    end
    resources :skills do
      member do
        get "delete"
      end
    end
    resources :topics do
      member do
        get "delete"
      end
    end
    resources :systemmetas do
      member do
        get "delete"
      end
      get :permission, :on => :collection
      get :market, :on => :collection
      post :marketing, :on => :collection
      post :updates, :on => :collection
    end
    resources :messages do
      member do
        post "read"
      end
      collection do
        get "t/:topic"=>"messages#topic",:as=>"t"
        get "sent"
      end
    end
    resources :users do
      member do
        get "delete"
        get "block"
        get "unblock"
      end
    end
    resources :chat_messages do
      collection do
        get "get_chat_users"
      end
    end 
    resources :permissions
    resources :reminders
    match '/statistics' => 'pages#general'
    match '/statistics/leaderboard' => 'pages#leaderboard'
    match '/statistics/online_ops' => 'pages#online_ops'
    match '/statistics/message_history' => 'pages#message_history'
    match '/statistics/payment_for_ops' => 'pages#payment_for_ops'
    match '/statistics/notes_history' => 'pages#notes_history'
  end
  match "api/login" => 'webservise#login'
  match "api/register" => 'webservise#register'
  match "api/forgotpassword" => 'webservise#forgotpassword'
  match "api/getalloperators" => 'webservise#getalloperators'
  match "api/getrandomagent" => 'webservise#getrandomagent'
  match "api/getlastagent" => 'webservise#getlastagent'
  match "api/getfavoriteoperators" => 'webservise#getfavoriteoperators'
  match "api/getoperatorinfo" => 'webservise#getoperatorinfo'
  match "api/changepassword" => 'webservise#changepassword'
  match "api/changeavatar" => 'webservise#changeavatar'
  match "api/setusercredit" => 'webservise#setusercredit'
  match "api/setrate" => 'webservise#setrate'
  match "api/getrecentoperators" => 'webservise#getrecentoperators'
  match "api/favoriteoperator" => 'webservise#favoriteoperator'
  match "api/unfavoriteoperator" => 'webservise#unfavoriteoperator'
  match "api/getmessagelist" => 'webservise#getmessagelist'
  match "api/sendmessage" => 'webservise#sendmessage'
  match "api/sawdailymessage" => 'webservise#sawdailymessage'
  match "api/endsession" => 'webservise#endsession'
  match "api/getuserinfo" => 'webservise#getuserinfo'

  root :to => "admin/operators#index"

end

app/views/admin/_footer.html.erb
<div class="footer">
</div>

app/views/admin/_menubar.html.erb
<div class="mainleftinner">         
  <div class="leftmenu">
    <ul>
      <% if current_operator.has_role? :admin or current_operator.has_role? :superadmin %>
        <li class="<%= compare_url(admin_operators_path) %>">
          <%= link_to "<span><em>Operators</em></span>".html_safe, admin_operators_path, :class=>"users" %>
        </li>  
      <% end %>
      <% if current_operator.has_role? :admin or current_operator.has_role? :superadmin %>
        <li class="<%= compare_url(admin_users_path) %>">
          <%= link_to "<span><em>Users</em></span>".html_safe, admin_users_path, :class=>"editor" %>
        </li>
      <% end %>
      <% if current_operator.has_role? :admin or current_operator.has_role? :superadmin %>
        <li class="<%= compare_url(rota_index_admin_schedules_path) %>">
          <%= link_to "<span><em>Rota</em></span>".html_safe, rota_index_admin_schedules_path, :class=>"record" %>
        </li>
      <% end %>
      <li class="<%= compare_url(admin_schedules_path) %>">
        <%= link_to "<span><em>Schedule</em></span>".html_safe, admin_schedules_path, :class=>"record" %>
      </li>
      <li class="<%= compare_url(admin_messages_path) %>">
        <%= link_to "<span><em>Internal Message</em></span>".html_safe, admin_messages_path, :class=>"elements" %>
      </li>
      <% if current_operator.has_role? :admin or current_operator.has_role? :superadmin %>
        <li class="<%= compare_url(admin_skills_path) %>">
          <%= link_to "<span><em>Skills</em></span>".html_safe, admin_skills_path, :class=>"help" %>
        </li>
      <% end %>
      <% if current_operator.has_role? :admin or current_operator.has_role? :superadmin %>
        <li class="<%= compare_url(admin_pictures_path) %>">
          <%= link_to "<span><em>Pictures</em></span>".html_safe, admin_pictures_path, :class=>"photos" %>
        </li>
      <% end %>
      <% if current_operator.has_role? :admin or current_operator.has_role? :superadmin%>
        <li class="<%= compare_url(admin_systemmetas_path) %>">
          <%= link_to "<span><em>Settings</em></span>".html_safe, admin_systemmetas_path, :class=>"grid" %>
        </li>
      <% end %>
      <% if current_operator.has_role? :superadmin %>
        <li  class="<%= compare_url(admin_statistics_path) %>">
          <%= link_to "<span><em>Statistics</em></span>".html_safe, admin_statistics_path, :class=>"dashboard" %>
        </li>
      <% end %>
    </ul>
  </div><!--leftmenu-->
  <div id="togglemenuleft"><a></a></div>
</div>

app/views/admin/_sidebar.html.erb
<div class="mainrightinner">
            	
  <div class="widgetbox">
    <div class="title">
      <h2 class="chart"><span>Versions</span></h2>
    </div>
    <div class="widgetcontent announcement">
      <p>
        <span class="radius2">July 19, 2012</span> <br>
        Spytap Android Version 2.1 Complete                        
      </p>
    </div>
    <!--widgetcontent-->
  </div><!--widgetbox-->
  <br clear="all">
  <div class="widgetbox">
  <div class="title">
    <h2 class="tabbed"><span>Download Data</span></h2></div>
  <div class="widgetcontent padding0">
    <ul class="activitylist">
      <li class="help"><a href=""><strong>PDF</strong><span></span></a></li>
        <li class="csv"><a href=""><strong>CSV</strong><span></span></a></li>
        <li class="xls"><a href=""><strong>XLS</strong><span></span></a></li>

    </ul>
  </div><!--widgetcontent-->
  </div><!--widgetbox-->
</div>