config/routes.rb
VchatManage::Application.routes.draw do

  get "operators/index"

  devise_for :operators

  namespace :admin do
    resources :operators do
      member do
        get "delete"
        get "block"
        get "unblock"
        get "profile"
        get "permission"
        get "session_history"
        get "attendance_history"
        get "attendance_by_date/:date", :action=>"attendance_history", :as=>"attendance_by_date"
      end
      get :autocomplete_skill_name, :on => :collection
      get :message_history, :on => :collection
    end
    resources :pictures do
      member do
        get "delete"
      end
    end
    resources :schedules do
      member do
        get "delete"
      end
      collection do
        get "work_page"
        get "rota_index"
        get "rota_slot/:date/:number", :action=>"rota_slot",:as=>"rota_slot"
        get "cancel/:schedule", :action=>"cancel", :as=>"cancel"
        get "index_by_date/:date", :action=>"index", :as=>"index_by_date"
        get "rindex_by_date/:date", :action=>"rota_index", :as=>"rindex_by_date"
        post "add_operator"
        post "request_holidays"
        post "note"
      end
    end
    resources :skills do
      member do
        get "delete"
      end
    end
    resources :topics do
      member do
        get "delete"
      end
    end
    resources :systemmetas do
      member do
        get "delete"
      end
      get :permission, :on => :collection
      get :market, :on => :collection
      post :marketing, :on => :collection
      post :updates, :on => :collection
    end
    resources :messages do
      member do
        post "read"
      end
      collection do
        get "t/:topic"=>"messages#topic",:as=>"t"
        get "sent"
      end
    end
    resources :users do
      member do
        get "delete"
        get "block"
        get "unblock"
      end
    end
    resources :chat_messages do
      collection do
        get "get_chat_users"
      end
    end 
    resources :permissions
    resources :reminders
    match '/statistics' => 'pages#general'
    match '/statistics/leaderboard' => 'pages#leaderboard'
    match '/statistics/online_ops' => 'pages#online_ops'
    match '/statistics/message_history' => 'pages#message_history'
    match '/statistics/payment_for_ops' => 'pages#payment_for_ops'
    match '/statistics/notes_history' => 'pages#notes_history'
  end
  match "api/login" => 'webservise#login'
  match "api/register" => 'webservise#register'
  match "api/forgotpassword" => 'webservise#forgotpassword'
  match "api/getalloperators" => 'webservise#getalloperators'
  match "api/getrandomagent" => 'webservise#getrandomagent'
  match "api/getlastagent" => 'webservise#getlastagent'
  match "api/getfavoriteoperators" => 'webservise#getfavoriteoperators'
  match "api/getoperatorinfo" => 'webservise#getoperatorinfo'
  match "api/changepassword" => 'webservise#changepassword'
  match "api/changeavatar" => 'webservise#changeavatar'
  match "api/setusercredit" => 'webservise#setusercredit'
  match "api/setrate" => 'webservise#setrate'
  match "api/getrecentoperators" => 'webservise#getrecentoperators'
  match "api/favoriteoperator" => 'webservise#favoriteoperator'
  match "api/unfavoriteoperator" => 'webservise#unfavoriteoperator'
  match "api/getmessagelist" => 'webservise#getmessagelist'
  match "api/sendmessage" => 'webservise#sendmessage'
  match "api/sawdailymessage" => 'webservise#sawdailymessage'
  match "api/endsession" => 'webservise#endsession'
  match "api/getuserinfo" => 'webservise#getuserinfo'

  root :to => "admin/operators#index"

end

app/models/systemmeta.rb
class Systemmeta < ActiveRecord::Base
  attr_accessible :default, :display_name, :meta_key, :meta_value
  validates :meta_key, :uniqueness => true
 
  def event_start_end_datetime
  end
  def self.get_setting(name)
    setting = Systemmeta.find_or_initialize_by_meta_key(name)
    return setting.meta_value
  end
  def self.push_user_daily_messages
    key = "push_user_daily_messages"
    value = DateTime.now
    value = value.to_s
    setting = Systemmeta.find_or_initialize_by_meta_key(key)
    setting.update_attributes(
      :meta_key => key,
      :meta_value => value
    )    
    unless Systemmeta.get_setting("user_daily_message") ==  Systemmeta.get_setting("_user_daily_message")
      setting = Systemmeta.find_or_initialize_by_meta_key("_user_daily_message")
      setting.update_attributes(
        :meta_key => "_user_daily_message",
        :meta_value => Systemmeta.get_setting("user_daily_message")
      )
      user_daily_message = Systemmeta.get_setting("user_daily_message")
      users = User.where(:daily_message=>false)
      User.daily_messages(user_daily_message)
    end    
  end
end

app/controllers/admin/systemmetas_controller.rb
class Admin::SystemmetasController < ApplicationController
  include ApplicationHelper
  layout "admin"
  before_filter :authenticate_operator!  
  before_filter :authorize_admin!
  def index
    @settings = Systemmeta.all
  end
  def show
  end
  def new
    @systemmeta = Systemmeta.new
  end
  def create
    @settings = params[:settings]
    @settings.each do | key, value |
      setting = Systemmeta.find_or_initialize_by_meta_key(key)
      setting.update_attributes(
        :meta_key => key,
        :meta_value => value
      )
    end
    render "index"
  end
  def permission
    @operators  = Operator.operators
    @admins     = Operator.admins
    @settings = Systemmeta.all
    @operator = @operators.first
    @permission = @operator.get_permission
    render "permission"
  end
  def market
    @reminders = Reminder.all
    @settings = Hash.new
    @settings['operator_daily_message'] = Systemmeta.get_setting("operator_daily_message")
    @settings['user_daily_message'] = Systemmeta.get_setting("user_daily_message")
    render "market"
  end
  def marketing
    @settings = params[:settings]
    operator_daily_message = @settings['operator_daily_message']
    user_daily_message = @settings['user_daily_message']
    update = false
    unless operator_daily_message ==  Systemmeta.get_setting("operator_daily_message")
      setting = Systemmeta.find_or_initialize_by_meta_key("_operator_daily_message")
      setting.update_attributes(
        :meta_key => "_operator_daily_message",
        :meta_value => Systemmeta.get_setting("operator_daily_message")
      )
      setting = Systemmeta.find_or_initialize_by_meta_key("operator_daily_message")
      setting.update_attributes(
        :meta_key => "operator_daily_message",
        :meta_value => operator_daily_message
      )
      update = true
      operators = Operator.where(:block=>false)
      operators.each do |operator|
        next if operator == current_operator
        topic = Topic.where("subject = 'Daily Message' and recipient_id = ? and sender_id = ?",operator.id, current_operator.id ).first
        if topic.nil?
          topic = Topic.new
          topic.subject = "Daily Message"
          topic.recipient = operator
          topic.sender = current_operator
          topic.save
        end
        msg = Message.new()
        msg.recipient = operator
        msg.sender = current_operator
        msg.topic = topic
        msg.message = operator_daily_message
        saved = msg.save      
      end  
    end
=begin    
    unless user_daily_message ==  Systemmeta.get_setting("user_daily_message")
      setting = Systemmeta.find_or_initialize_by_meta_key("_user_daily_message")
      setting.update_attributes(
        :meta_key => "_user_daily_message",
        :meta_value => Systemmeta.get_setting("user_daily_message")
      )
      setting = Systemmeta.find_or_initialize_by_meta_key("user_daily_message")
      setting.update_attributes(
        :meta_key => "user_daily_message",
        :meta_value => user_daily_message
      )
      update = true
      users = User.where(:daily_message=>false)
      User.daily_messages(user_daily_message)
    end
=end    
    if update 
      render :js=>"alert('Successfully updated')"
    else
      render :js=>""
    end
  end
  def updates
    checked_settings = ['outsite_shift_op','notes_op','order_op','schedule_op','editable_profile_admin','character_profile_admin',
      'mass_sending_admin','kickop_admin','editable_note_admin','answer_users_admin']
    @settings = params[:settings]
    date_errors = false
    if @settings.has_key?("schedule_start_date_op") && @settings.has_key?("schedule_end_date_op")
      start_date = @settings["schedule_start_date_op"]
      end_date = @settings["schedule_end_date_op"]
      if start_date > end_date
        date_errors = true
        @settings.delete("schedule_start_date_op")
        @settings.delete("schedule_end_date_op")
      end
    end
    checked_settings.each do |key|
      if @settings.has_key?(key)
        value = 1
      else
        value = 0
      end
      setting = Systemmeta.find_or_initialize_by_meta_key(key)
      setting.update_attributes(
        :meta_key => key,
        :meta_value => value
      )
    end
    @settings.each do | key, value |
      setting = Systemmeta.find_or_initialize_by_meta_key(key)
      unless checked_settings.include?(key)
        setting.update_attributes(
          :meta_key => key,
          :meta_value => value
        )
      end
    end  
    if date_errors 
      flash[:alert] = "can't be earlier then start date time"
    else
      flash[:success] = "Successfully updated"
    end
    redirect_to permission_admin_systemmetas_path
  end
  private
    def authorize_admin!
      unless current_operator.has_role? :admin or current_operator.has_role? :superadmin
        flash[:alert] = "You must be an admin to do that."
        redirect_to admin_schedules_path
      end
    end
end

app/helpers/admin/systemmetas_helper.rb
module Admin::SystemmetasHelper
  def get_setting(name)
    setting = Systemmeta.find_or_initialize_by_meta_key(name)
    return setting.meta_value
  end
end

app/views/admin/systemmetas/index.html.erb
<% content_for :menu do %>
  <ul class='maintabmenu'>
    <li class='current'><a href='javascript:void(0)'>Overview</a></li>
    <li><%= link_to "Permissions", permission_admin_systemmetas_path %></li>
    <li><%= link_to "Marketing", market_admin_systemmetas_path %></li>
  </ul>
<% end %>
<div class="contenttitle">
  <h2 class="form"><span>Overview</span></h2>
</div>
<%=  form_for(updates_admin_systemmetas_path,:html => { :class => "stdform " }) do |f| %>
  <p>
    <label class="settings">Minimum Character Length</label>
    <span class="field">
      <input type="text" class="tinyinput" name="settings[min_length]" value="<%= get_setting('min_length') %>">
    </span>
  </p>
  <p>
    <label class="settings">Maximum Character Length</label>
    <span class="field">
      <input type="text" class="tinyinput" name="settings[max_length]" value="<%= get_setting('max_length')%>">
    </span>
  </p>
  <p>
    <label class="settings">User Waiting time to alert op</label>
    <span class="field">
      <input type="text" class="tinyinput" name="settings[waiting_time]" value="<%= get_setting('waiting_time')%>">
    </span>
  </p>
  <p>
    <label class="settings">Inactivity time before op is kicked from work page</label>
    <span class="field">
      <input type="text" class="tinyinput" name="settings[inactivity_time]" value="<%= get_setting('inactivity_time')%>">
    </span>
  </p>
  <p>
    <label class="settings">Minutes logging in – late</label>
    <span class="field">
      <input type="text" class="tinyinput" name="settings[late_setting]" value="<%= get_setting('late_setting')%>">
    </span>
  </p>
  <p>
    <label class="settings">Session end time</label>
    <span class="field">
      <input type="text" class="tinyinput" name="settings[session_end_time]" value="<%= get_setting('session_end_time')%>"> Minutes
    </span>
  </p>
  <p>
    <label class="settings">Maximum number of users an op can have at any one time</label>
    <span class="field">
      <input type="text" class="tinyinput" name="settings[max_users_per_request]" value="<%= get_setting('max_users_per_request')%>">
    </span>
  </p>
  <p>
    <label class="settings">Monetary values for payscale a b and c </label>
    <span class="field">
      <input type="text" class="tinyinput" name="settings[payscale_a]" value="<%= get_setting('payscale_a')%>">
      <input type="text" class="tinyinput" name="settings[payscale_b]" value="<%= get_setting('payscale_b')%>">
      <input type="text" class="tinyinput" name="settings[payscale_c]" value="<%= get_setting('payscale_c')%>">
    </span>
  </p>
  <p>
    <label class="settings">Rating bandings for payscale a b and c </label>
    <span class="field">
      <input type="text" class="tinput" name="settings[rating_banding_a_start]" value="<%= get_setting('rating_banding_a_start')%>">
      <input type="text" class="tinput" name="settings[rating_banding_a_end]" value="<%= get_setting('rating_banding_a_end')%>">
      <input type="text" class="tinput" name="settings[rating_banding_b_start]" value="<%= get_setting('rating_banding_b_start')%>">
      <input type="text" class="tinput" name="settings[rating_banding_b_end]" value="<%= get_setting('rating_banding_b_end')%>">
      <input type="text" class="tinput" name="settings[rating_banding_c_start]" value="<%= get_setting('rating_banding_c_start')%>">
      <input type="text" class="tinput" name="settings[rating_banding_c_end]" value="<%= get_setting('rating_banding_c_end')%>">
    </span>
  </p>
  <p>
    <label class="settings">Rota opening times</label>
    <span class="field">
      <input type="text" class="tinyinput date-pick" name="settings[rota_start_date]" data-date-format="dd-mm-yyyy" value="<%= get_setting('rota_start_date')%>">
      <input type="text" class="tinyinput date-pick" name="settings[rota_end_date]" data-date-format="dd-mm-yyyy" value="<%= get_setting('rota_end_date')%>">
    </span>
  </p>
  <p>
    <label class="settings">Time allowed for cancellation requests</label>
    <span class="field">
      <input type="text" class="tinyinput" name="settings[allow_cancel]" value="<%= get_setting('allow_cancel')%>">
    </span>
  </p>
  <p>
    <label class="settings">Target hours</label>
    <span class="field">
      <input type="text" class="tinyinput" name="settings[target_hours]" value="<%= get_setting('target_hours')%>">
    </span>
  </p>
  <!--<p>
    <label class="settings">Number of weeks below target hours in any given month</label>
      <span class="field"><input type="text" class="tinyinput" name="input2"></span>
  </p>-->
  <p>
    <label class="settings">number of days when Notes will be stored</label>
    <span class="field">
      <input type="text" class="tinyinput" name="settings[notes_stored]" value="<%= get_setting('notes_stored')%>">
    </span>
  </p>
  <p>
    <label class="settings">Free Credit Count</label>
    <span class="field">
      <input type="text" class="tinyinput" name="settings[free_credits]" value="<%= get_setting('free_credits')%>">
    </span>
  </p>
  <p class="stdformbutton">
    <button class="submit radius2">Submit Button</button>
  </p>
<%  end %>

app/views/admin/systemmetas/market.html.erb
<% content_for :menu do %>
  <ul class='maintabmenu'>
    <li><%= link_to "Overview", admin_systemmetas_path %></li>
    <li><%= link_to "Permissions", permission_admin_systemmetas_path %></li>
    <li class='current'><a href='javascript:void(0)'>Marketing</a></li>
  </ul>
<% end %>
<div class="contenttitle">
  <h2 class="form"><span>Message of Day</span></h2>
</div>
<%= form_tag(marketing_admin_systemmetas_path, :method => :post,:class => "stdform market_setting",:remote => true) do %>
  <table cellspacing="0" cellpadding="0" border="0" class="stdtable">
    <colgroup>
      <col class="con0">
      <col class="con1">
    </colgroup>
    <thead>
      <tr>
        <th class="head0">For operators</th>
        <th class="head1">For users</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="con0">
          <p>
            <span class="field"><textarea name="settings[operator_daily_message]" class="longinput" rows="5" cols="80"><%= get_setting('operator_daily_message') %></textarea></span> 
          </p>          
        </td>
        <td class="con1">
          <p>
            <span class="field"><textarea name="settings[user_daily_message]" class="longinput" rows="5" cols="80"><%= get_setting('user_daily_message') %></textarea></span> 
          </p>          
        </td>
      </tr>
      <tr>
        <td class="con0" colspan="2">
          <p style="margin-left: 40%;">
            <button class="submit radius2">Save</button>
          </p>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>  
<div class="contenttitle">
  <h2 class="form"><span>Reminder list</span></h2>
</div>
<div class="actionBar">
  <%= link_to "Add new Reminder",new_admin_reminder_path, :remote =>true %>
</div>
<div id="modal-reminder">
</div>
<table cellspacing="0" cellpadding="0" border="0" class="stdtable">
  <colgroup>
    <col class="con0">
    <col class="con1">
    <col class="con0">
    <col class="con1">
    <col class="con0">
  </colgroup>
  <thead>
    <tr>
      <th class="head0">No</th>
      <th class="head1">Name</th>
      <th class="head0">Inactivity</th>
      <th class="head1">Time sent</th>
      <th class="head0">Spread</th>
      <th class="head0">No of Users</th>
      <th class="head1">Message</th>
      <th class="head0">Action</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th class="head0">No</th>
      <th class="head1">Name</th>
      <th class="head0">Inactivity</th>
      <th class="head1">Time sent</th>
      <th class="head0">Spread</th>
      <th class="head0">No of Users</th>
      <th class="head1">Message</th>
      <th class="head0">Action</th>
    </tr>
  </tfoot>
  <tbody id="reminder_list">
    <%= render :partial=>"admin/reminders/list" %>
  </tbody>
</table>

app/views/admin/systemmetas/permission.html.erb
<% content_for :menu do %>
  <ul class='maintabmenu'>
    <li><%= link_to "Overview", admin_systemmetas_path %></li>
    <li class='current'><a href='javascript:void(0)'>Permissions</a></li>
    <li><%= link_to "Marketing", market_admin_systemmetas_path %></li>
  </ul>
<% end %>
<table style="width:100%;">
  <tr>
    <td width="50%">
      <div id="tabs">
        <ul>
          <li><a href="#tabs-1">Operators</a></li>
          <li><a href="#tabs-2">Admins</a></li>
        </ul>
        <div id="tabs-1" class="ui-tabs-panel ui-widget-content ui-corner-bottom">
          <div class="contenttitle radiusbottom0">
            <h2 class="table"><span>Operations List</span></h2>
          </div>      
          <table cellspacing="0" cellpadding="0" border="0" class="stdtable">
            <colgroup>
              <col class="con0">
              <col class="con1">
            </colgroup>
            <thead>
              <tr>
                <th class="head0">Login Number</th>
                <th class="head1">Op Name</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th class="head0">Login Number</th>
                <th class="head1">Op Name</th>
              </tr>
            </tfoot>
            <tbody>
              <% @operators.each do |op|  %>
                <tr>
                  <td><%= link_to op.name, permission_admin_operator_path(op), :remote=>true %>&nbsp;</td>
                  <td><%= op.real_name%>&nbsp;</td>
                </tr>
              <% end %>
              <tr>
                <td class="con0">&nbsp;</td>
                <td class="con1">&nbsp;</td>
              </tr>
              <tr>
                <td class="con0">&nbsp;</td>
                <td class="con1">&nbsp;</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div id="tabs-2" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">
          <div class="contenttitle radiusbottom0">
            <h2 class="table"><span>Admins List</span></h2>
          </div>      
          <table cellspacing="0" cellpadding="0" border="0" class="stdtable">
            <colgroup>
              <col class="con0">
              <col class="con1">
            </colgroup>
            <thead>
              <tr>
                <th class="head0">Login Number</th>
                <th class="head1">Op Name</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th class="head0">Login Number</th>
                <th class="head1">Op Name</th>
              </tr>
            </tfoot>
            <tbody>
              <% @admins.each do |op|  %>
                <tr>
                  <td><%= link_to op.name, permission_admin_operator_path(op), :remote=>true %>&nbsp;</td>
                  <td><%= op.real_name%>&nbsp;</td>
                </tr>
              <% end %>
              <tr>
                <td class="con0">&nbsp;</td>
                <td class="con1">&nbsp;</td>
              </tr>
              <tr>
                <td class="con0">&nbsp;</td>
                <td class="con1">&nbsp;</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div id="operator_permission">
        <%= render :partial=>"admin/operators/permission" %>
      </div>
    </td>
    <td width="50%">
      <div class="contenttitle">
        <h2 class="form"><span>Default Operator Permisson</span></h2>
      </div>
      <%= form_tag(updates_admin_systemmetas_path, :method => :post,:class => "stdform permission_setting") do %>
        <p>
          <span class="fieldcheckbox">
            <input type="checkbox" class="smallinput" name="settings[outsite_shift_op]" <%= "checked" if get_setting('outsite_shift_op') == "1" %> value="outsite_shift_op">
          </span>
          <span>Can access work page outside of shifts</span>
        </p>
        <p>
          <span class="fieldcheckbox">
            <input type="checkbox" class="smallinput" name="settings[notes_op]" <%= "checked" if get_setting('notes_op') == "1" %> value="notes_op">
          </span>
          <span>Can view notes</span>
        </p>
        <p>
          <label class="permission" style="width:165px;">Idle time before kicked</label>
          <span class="field">
            <%= select_tag "settings[idle_time_op]", options_idle_times(get_setting('idle_time_op')) %>
          </span>
        </p>
        <p>
          <span class="fieldcheckbox">
            <input type="checkbox" class="smallinput" name="settings[schedule_op]" <%= "checked" if get_setting('schedule_op') == "1" %> value="schedule_op">
          </span>
          <span>Can acess schedule</span>
        </p>
        <p>
          <label class="permission">between</label>
          <span class="field" style="display:inline;">
            <input type="text" class="datestart date-pick"  style="width:77px;" name="settings[schedule_start_date_op]" value="<%= get_setting('schedule_start_date_op')%>">
          </span>
          <label style="float:none;">&nbsp;&nbsp;and</label>
          <span class="field" style="display:inline;">
            <input type="text" class="dateend date-pick" style="width:77px;"  name="settings[schedule_end_date_op]" value="<%= get_setting('schedule_end_date_op')%>">
          </span>
        </p>
      <div class="contenttitle">
        <h2 class="form"><span>Default Admin Permisson</span></h2>
      </div>
        <p>
          <span class="fieldcheckbox">
            <input type="checkbox" class="smallinput" name="settings[editable_profile_admin]" <%= "checked" if get_setting('editable_profile_admin') == "1" %> value="editable_profile_admin">
          </span>
          <span>Can edit identity profile(real details)</span>
        </p>
        <p>
          <span class="fieldcheckbox">
            <input type="checkbox" class="smallinput" name="settings[character_profile_admin]" <%=  "checked" if get_setting('character_profile_admin') == "1" %> value="character_profile_admin">
          </span>
          <span>Can edit character profile</span>
        </p>
        <p>
          <span class="fieldcheckbox">
            <input type="checkbox" class="smallinput" name="settings[mass_sending_admin]" <%= "checked" if get_setting('mass_sending_admin') == "1" %> value="mass_sending_admin">
          </span>
          <span>Can add and edit content for mass sending</span>
        </p>
        <p>
          <span class="fieldcheckbox">
            <input type="checkbox" class="smallinput" name="settings[kickop_admin]" <%= "checked" if get_setting('kickop_admin') == "1" %> value="kickop_admin">
          </span>
          <span>Can kick op from workpage</span>
        </p>
        <p>
          <span class="fieldcheckbox">
            <input type="checkbox" class="smallinput" name="settings[editable_note_admin]" <%= "checked" if get_setting('editable_note_admin') == "1" %> value="editable_note_admin">
          </span>
          <span>Can view and edit notes</span>
        </p>
        <p class="stdformbutton">
          <button class="submit radius2">Save</button>
        </p>
      <% end %>
    </td>
  </tr>
</table>