config/routes.rb
VchatManage::Application.routes.draw do

  get "operators/index"

  devise_for :operators

  namespace :admin do
    resources :operators do
      member do
        get "delete"
        get "block"
        get "unblock"
        get "profile"
        get "permission"
        get "session_history"
        get "attendance_history"
        get "attendance_by_date/:date", :action=>"attendance_history", :as=>"attendance_by_date"
      end
      get :autocomplete_skill_name, :on => :collection
      get :message_history, :on => :collection
    end
    resources :pictures do
      member do
        get "delete"
      end
    end
    resources :schedules do
      member do
        get "delete"
      end
      collection do
        get "work_page"
        get "rota_index"
        get "rota_slot/:date/:number", :action=>"rota_slot",:as=>"rota_slot"
        get "cancel/:schedule", :action=>"cancel", :as=>"cancel"
        get "index_by_date/:date", :action=>"index", :as=>"index_by_date"
        get "rindex_by_date/:date", :action=>"rota_index", :as=>"rindex_by_date"
        post "add_operator"
        post "request_holidays"
        post "note"
      end
    end
    resources :skills do
      member do
        get "delete"
      end
    end
    resources :topics do
      member do
        get "delete"
      end
    end
    resources :systemmetas do
      member do
        get "delete"
      end
      get :permission, :on => :collection
      get :market, :on => :collection
      post :marketing, :on => :collection
      post :updates, :on => :collection
    end
    resources :messages do
      member do
        post "read"
      end
      collection do
        get "t/:topic"=>"messages#topic",:as=>"t"
        get "sent"
      end
    end
    resources :users do
      member do
        get "delete"
        get "block"
        get "unblock"
      end
    end
    resources :chat_messages do
      collection do
        get "get_chat_users"
      end
    end 
    resources :permissions
    resources :reminders
    match '/statistics' => 'pages#general'
    match '/statistics/leaderboard' => 'pages#leaderboard'
    match '/statistics/online_ops' => 'pages#online_ops'
    match '/statistics/message_history' => 'pages#message_history'
    match '/statistics/payment_for_ops' => 'pages#payment_for_ops'
    match '/statistics/notes_history' => 'pages#notes_history'
  end
  match "api/login" => 'webservise#login'
  match "api/register" => 'webservise#register'
  match "api/forgotpassword" => 'webservise#forgotpassword'
  match "api/getalloperators" => 'webservise#getalloperators'
  match "api/getrandomagent" => 'webservise#getrandomagent'
  match "api/getlastagent" => 'webservise#getlastagent'
  match "api/getfavoriteoperators" => 'webservise#getfavoriteoperators'
  match "api/getoperatorinfo" => 'webservise#getoperatorinfo'
  match "api/changepassword" => 'webservise#changepassword'
  match "api/changeavatar" => 'webservise#changeavatar'
  match "api/setusercredit" => 'webservise#setusercredit'
  match "api/setrate" => 'webservise#setrate'
  match "api/getrecentoperators" => 'webservise#getrecentoperators'
  match "api/favoriteoperator" => 'webservise#favoriteoperator'
  match "api/unfavoriteoperator" => 'webservise#unfavoriteoperator'
  match "api/getmessagelist" => 'webservise#getmessagelist'
  match "api/sendmessage" => 'webservise#sendmessage'
  match "api/sawdailymessage" => 'webservise#sawdailymessage'
  match "api/endsession" => 'webservise#endsession'
  match "api/getuserinfo" => 'webservise#getuserinfo'

  root :to => "admin/operators#index"

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :operator
  attr_accessible :number, :thedate, :status, :operator_id
  validates :number, :numericality => { :only_integer => true, :greater_than_or_equal_to=>0, :less_than=>25 }
  validates_uniqueness_of :operator_id, :scope => [:thedate, :number]  
  OPCOUNT = 3
  def current_status
    today = Date.today
    if today > self.thedate or (today == self.thedate and Time.now.strftime("%H").to_i >= self.number)
      return "absence" if self.status == "booked"
    end 
    return self.status
  end
  def self.workable_ops
    ops = where(:thedate=>Date.today, :number=>Time.now.strftime("%H").to_i).where("status='attend' or status='late' or status='booked'" )
  end
end

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < ApplicationController
  layout "admin"
  before_filter :authenticate_operator!  
  before_filter :authorize_admin! , :only => [:rota_index,:cancel]
  def index
    @thedate = Date.today
    @thedate = params[:date].to_date if params[:date]
    begindate = @thedate.beginning_of_week
    @schedules = Array.new
    @allow_cancel = Systemmeta.get_setting('allow_cancel')
    @op_schedules = []
    (0..6).each do |w|
      @schedules[w] = Array.new
      @op_schedules[w] = []
      (0..23).each do |num|
        @schedules[w][num] = Schedule.where(:thedate=>begindate+w, :number=>num)
        @op_schedules[w][num] = Schedule.where(:thedate=>begindate+w, :number=>num, :operator_id=>current_operator.id).first_or_initialize
      end  
    end    
  end
  def rota_index
    @thedate = Date.today
    @thedate = params[:date].to_date if params[:date]
    begindate = @thedate.beginning_of_week
    @schedules = Array.new
    @op_schedules = []
    (0..6).each do |w|
      @schedules[w] = Array.new
      @op_schedules[w] = []
      (0..23).each do |num|
        @schedules[w][num] = Hash.new
        record = Schedule.where(:thedate=>begindate+w, :number=>num, :operator_id =>0).first
        op_count = Schedule::OPCOUNT
        op_count = record.status unless record.nil?
        @schedules[w][num][:total_count] =  op_count
        statuses = Schedule.where(:thedate=>begindate+w, :number=>num )
        today = Date.today
        if today > begindate+w
          attend_count = Schedule.where(:thedate=>begindate+w, :number=>num, :status=>"attend" ).count
          late_count = Schedule.where(:thedate=>begindate+w, :number=>num, :status=>"late" ).count
          absent_count = Schedule.where(:thedate=>begindate+w, :number=>num, :status=>"booked" ).count
          current_count = attend_count + late_count + absent_count
        elsif today == (begindate+w) and Time.now.strftime("%H").to_i >= num
          attend_count = Schedule.where(:thedate=>begindate+w, :number=>num, :status=>"attend" ).count
          late_count = Schedule.where(:thedate=>begindate+w, :number=>num, :status=>"late" ).count
          absent_count = Schedule.where(:thedate=>begindate+w, :number=>num, :status=>"booked" ).count
          current_count = attend_count + late_count + absent_count
        else  
          current_count = Schedule.where(:thedate=>begindate+w, :number=>num, :status=>"booked" ).count
        end
        @schedules[w][num][:count] =  current_count
      end  
    end    
    @number = Time.now.strftime("%H").to_i
    @schedules_per_slot = Schedule.where(:thedate=>@thedate, :number=>@number )
    @op_count = Schedule::OPCOUNT
    record = Schedule.where(:thedate=>@thedate, :number=>@number, :operator_id =>0).first
    @op_count = record.status unless record.nil?
    @operators = Operator.operators
  end
  def show
  end
  def rota_slot
    @thedate = params[:date].to_date
    @number = params[:number].to_i
    @schedules_per_slot = Schedule.where(:thedate=>@thedate, :number=>@number )
    @op_count = Schedule::OPCOUNT
    record = Schedule.where(:thedate=>@thedate, :number=>@number, :operator_id =>0).first
    @op_count = record.status unless record.nil?
    @td_id = nil
    render :action=>:rota_slot, :layout=>nil
  end
  def new
  end
  def cancel
    schedule = Schedule.find(params[:schedule])
    today = Date.today
    if today < schedule.thedate or (today == schedule.thedate and Time.now.strftime("%H").to_i < schedule.number)
      case schedule.current_status
      when "booked"
        schedule.status = "cancel_by_admin"
      when "cancel_by_admin"
        schedule.status = "booked"
      end  
      schedule.save
    end
    @thedate = schedule.thedate
    @number = schedule.number.to_i
    @week = @thedate.strftime("%u").to_i - 1
    record = Schedule.where(:thedate=>@thedate, :number=>@number, :operator_id =>0).first
    op_count = Schedule::OPCOUNT
    op_count = record.status unless record.nil?
    @total_count =  op_count
    statuses = Schedule.where(:thedate=>@thedate, :number=>@number )
    today = Date.today
    if today > @thedate or (today == @thedate and Time.now.strftime("%H").to_i > @number )
      attend_count = Schedule.where(:thedate=>@thedate, :number=>@number, :status=>"attend" ).count
      late_count = Schedule.where(:thedate=>@thedate, :number=>@number, :status=>"late" ).count
      absent_count = Schedule.where(:thedate=>@thedate, :number=>@number, :status=>"booked" ).count
      @current_count = attend_count + late_count + absent_count
    else  
      @current_count = Schedule.where(:thedate=>@thedate, :number=>@number, :status=>"booked" ).count
    end
    s=""
    if @current_count > 0
      s = "full_fill"
      if @total_count.to_i > @current_count
        s = "full_not"
      end
    end
    @td_id = 'td_'+@week.to_s+'_'+@number.to_s
    @schedules_per_slot = Schedule.where(:thedate=>@thedate, :number=>@number )
    @op_count = Schedule::OPCOUNT
    record = Schedule.where(:thedate=>@thedate, :number=>@number, :operator_id =>0).first
    @op_count = record.status unless record.nil?
    render :action=>:rota_slot, :layout=>nil
  end
  def add_operator
    op_count = params[:op_count]
    op_name  = params[:op_name]
    @thedate = params[:thedate].to_date
    @number = params[:number].to_i
    if op_count.to_i > 0
      s = Schedule.where(:thedate=>@thedate, :number=>@number, :operator_id =>0).first_or_create!(:status=>op_count)
      s.update_attributes(
        :status=>op_count
      )
    end
    operator = Operator.find_by_name(op_name)
    unless operator.nil?
      Schedule.where(:thedate=>@thedate, :number=>@number, :operator_id =>operator.id).first_or_create!(:status=>"booked")
    end
    @week = @thedate.strftime("%u").to_i - 1
    record = Schedule.where(:thedate=>@thedate, :number=>@number, :operator_id =>0).first
    op_count = Schedule::OPCOUNT
    op_count = record.status unless record.nil?
    @total_count =  op_count
    statuses = Schedule.where(:thedate=>@thedate, :number=>@number )
    today = Date.today
    if today > @thedate or (today == @thedate and Time.now.strftime("%H").to_i > @number )
      attend_count = Schedule.where(:thedate=>@thedate, :number=>@number, :status=>"attend" ).count
      late_count = Schedule.where(:thedate=>@thedate, :number=>@number, :status=>"late" ).count
      absent_count = Schedule.where(:thedate=>@thedate, :number=>@number, :status=>"booked" ).count
      @current_count = attend_count + late_count + absent_count
    else  
      @current_count = Schedule.where(:thedate=>@thedate, :number=>@number, :status=>"booked" ).count
    end
    s=""
    if @current_count > 0
      s = "full_fill"
      if @total_count.to_i > @current_count
        s = "full_not"
      end
    end
    @td_id = 'td_'+@week.to_s+'_'+@number.to_s
    @schedules_per_slot = Schedule.where(:thedate=>@thedate, :number=>@number )
    @op_count = Schedule::OPCOUNT
    record = Schedule.where(:thedate=>@thedate, :number=>@number, :operator_id =>0).first
    @op_count = record.status unless record.nil?
    render :action=>:rota_slot, :layout=>nil
  end
  def create
    @schedule = Schedule.new(params[:schedule])
    @schedule.status = "booked"
    @schedule.save
    @element_id = params[:element_id]
    @allow_cancel = Systemmeta.get_setting('allow_cancel')
    render :action=>:create, :layout=>nil
    #render :js=>"alert('success!');" and return
  end
  def update
  end
  def destroy
    @sh = Schedule.find(params[:schedule][:id])
    @sh.destroy
    params[:schedule].delete(:id)
    @schedule = Schedule.new(params[:schedule])
    @element_id = params[:element_id]
    render :action=>:destroy, :layout=>nil
  end
  def work_page
    current_hour = Time.now.strftime("%H").to_i
    today = Date.today
    record = Schedule.where(:thedate=>today, :number=>current_hour, :operator_id=>current_operator.id).first
    if record.nil?
      #"your page block"
      @working_status = false;
    else 
      case record.status
      when "booked"
        late_time = Systemmeta.get_setting('late_setting')
        current_minute = Time.now.strftime("%M").to_i
        if current_minute > late_time.to_i 
          record.status = "late"
        else  
          record.status = "attend"
        end
        record.save
        @working_status = true
      when "late","attend"  
        @working_status = true
      else
        @working_status = false
      end
    end
    @new_chat = ChatMessage.new
    @users = User.all
    @active_sessions = current_operator.active_sessions
    unless session.has_key?(:chat_user_id) || User.first.nil?
      session[:chat_user_id] = User.first.id
      session[:chat_user_id] = ChatMessage.last.user.id unless ChatMessage.last.nil?
    end    
    session[:read_time] = DateTime.now
    begin
      if session.has_key?(:chat_user_id)
        @chat_user = User.find(session[:chat_user_id]) 
        #@chat_messages = ChatMessage.where("created_at >= ? and user_id = ? and operator_id = ?",session[:read_time]-1.days,session[:chat_user_id],current_operator.id)
        active_session = Session.active_session(current_operator,@chat_user)
        if active_session.nil?
          @chat_messages = []
        else
          @chat_messages = active_session.chat_messages
        end
        @notes = Note.where("viewable = true and user_id = ? and operator_id = ?",session[:chat_user_id],current_operator.id)
      end
    rescue
      session.delete(:chat_user_id) 
      @chat_messages = []
    end
  end
  def request_holidays
    start_date  = Date.strptime(params[:start_date],"%m/%d/%Y")
    start_date =  Date.today +1 if start_date <= Date.today
    end_date    = Date.strptime(params[:end_date],"%m/%d/%Y")
    setting     = params[:setting]
    if start_date <= end_date
      case setting
      when "set"
        (start_date..end_date).each do |d|
          (0..23).each do |num|

app/helpers/admin/schedules_helper.rb
module Admin::SchedulesHelper
  def is_bookable(statuses, thedate, number)
    status = Hash.new
    op_count = Schedule::OPCOUNT
    count = 0
    statuses.each do |s|
      if s.operator_id > 0
        case s.status 
        when "attend"
          status["attend"] = s.operator_id
        when "lates"
          status["lates"] = s.operator_id
        when "booked"
          status["booked"] = s.operator_id
          count = count+1
        when "cancel_by_admin"
          status["cancel_by_admin"] = s.operator_id
        else 
          status["other"] = s.operator_id
        end  
      elsif s.operator_id == 0
        op_count = s.status.to_i
      end
      if s.operator_id == current_operator.id
        status["own"] = s.status
      end  
    end unless statuses.nil?
    today = Date.today
    if today > thedate or (today == thedate and Time.now.strftime("%H").to_i > number)
      case status["own"] 
      when "booked"
        return "absence"
      when "attend","late"
        return status["own"]
      else
        return ""
      end
    elsif status["own"]
      case status["own"]
      when "cancel_by_admin"
        return ""
      else
        return status["own"] 
      end
    end
    if op_count > count    
      return "bookable"
    else 
      return "full"
    end
  end
  def books_analyse(statuses, thedate, number)
    status = Hash.new
    statuses.each do |s|
      if s.operator.has_role? :admin
        
      else
        if s.operator_id > 0
          case s.status 
          when "attend"
            status["attend"] = s.operator_id
          when "lates"
            status["lates"] = s.operator_id
          when "booked"
            status["booked"] = s.operator_id
          when "cancel_by_admin"
            status["cancel_by_admin"] = s.operator_id
          else 
            status["other"] = s.operator_id
          end  
        end
        if s.operator_id == current_operator.id
          status["own"] = s.status
        end  
      end
    end unless statuses.nil?
    today = Date.today
    if today > thedate
      return ""
    elsif today == thedate and Time.now.strftime("%H").to_i > number
      return ""
    elsif status["own"]
      return status["own"]
    else  
      return "bookable"
    end
  end
end

app/views/admin/schedules/_book.html.erb
<span class="bookable_span" title="Book" >bookable
  <% 
    unless defined? new_schedule 
      new_schedule = @schedule
      id = @element_id
    end
  %>  
  <%= form_for [:admin, new_schedule], :remote=>true do |f| %>
    <input type="hidden" name="element_id" value="<%= id %>" />
    <%= f.hidden_field :thedate %>
    <%= f.hidden_field :number %>
    <%= f.hidden_field :operator_id %>
  <% end %>
</span>    

app/views/admin/schedules/_cancel.html.erb
<span class="booked_span" title="Cancel" >booked
  <% 
    unless defined? schedule 
      schedule = @schedule
      id = @element_id
    end
    nowtime = schedule.thedate.to_datetime.advance(:hours =>schedule.number)
    allow_cancel = DateTime.now.advance(:hours =>@allow_cancel.to_i)
    if nowtime > allow_cancel
  %>
      <%= form_for [:admin, schedule], :remote=>true, :method=>'delete' do |f| %>
        <input type="hidden" name="element_id" value="<%= id %>" />
        <%= f.hidden_field :id %>
        <%= f.hidden_field :thedate %>
        <%= f.hidden_field :number %>
        <%= f.hidden_field :operator_id %>
      <% end %>
  <% end %>
</span>    

app/views/admin/schedules/_note_history.html.erb
<% @notes.each do |note| %>
<p>
  <span class="radius2"><%= note.operator.real_name %>  <%= note.created_at.to_s %></span> 
  <br><%= note.note %></p>
<% end %>

app/views/admin/schedules/_rota_details_per_slot.html.erb
<div class="contenttitle radiusbottom0">
  <h2 class="table"><span>Detail data of selected slot(<%= @number.to_s+":00 "+@number.to_s+":59 of "+@thedate.strftime("%a, %d/%m") %> )</span></h2>
</div>  
<div class="tableoptions">
  <%= form_tag add_operator_admin_schedules_path, :remote=>true do %>
  <% today = Date.today 
    if today < @thedate or (today == @thedate and Time.now.strftime("%H").to_i < @number)  %>
      Op Count<input type="text" name="op_count" value="<%= @op_count.to_s %>">
      Op Name<input type="text" autocomplete="off"  class="focus" maxlength="20" placeholder="Name" name="op_name">
      <input type="hidden" name="thedate" value="<%= @thedate %>">
      <input type="hidden" name="number" value="<%= @number %>">
      <button class="radius3" id="operator_save" type="submit">Add Op Manually</button>
    <% else %>  
      Op Count<input type="text" name="op_count" value="<%= @op_count.to_s %>" disabled>
    <% end %>  
  <% end %>    
</div>  
<table cellspacing="0" cellpadding="0" border="0" class="stdtable stdtablecb" id="table1">
  <thead>
    <tr>
      <th class="head1">Login number</th>
      <th class="head0">Op name</th>
      <th class="head1">Email Address</th>
      <th class="head0">Status(Attendance, Late, Absence, Booked)</th>
      <th class="head1">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @schedules_per_slot.each do |schedule| %>
      <% next if schedule.operator_id == 0 
        today = Date.today %>
      <tr>
        <td><%= schedule.operator.name  %>&nbsp;</td>
        <td><%= schedule.operator.display_name  %>&nbsp;</td>
        <td><%= schedule.operator.email  %></td>
        <td><%= schedule.current_status  %>&nbsp;</td>
        <td><%= 
              if today < schedule.thedate or (today == schedule.thedate and Time.now.strftime("%H").to_i < schedule.number)
                case schedule.current_status
                when "booked"
                  link_to("Cancel",cancel_admin_schedules_path(schedule),:remote=>true ) 
                when "cancel_by_admin"
                  link_to("Active",cancel_admin_schedules_path(schedule),:remote=>true ) 
                end  
              end
          %>&nbsp;</td>
      </tr>
    <% end %>
    <% [1,2,3].each do |index| %>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    <% end %>  
  </tbody>
</table>  

app/views/admin/schedules/_slot.html.erb
<% 
  s=""
  if @current_count>0
    s = "full_fill"
    if @total_count.to_i > @current_count
      s = "full_not"
    end
  end
%>
<td class="<%= s %>" id="td_<%=  (@week.to_s+"_"+@number.to_s) %>">
  <span class="<%= s %>_span" ><%= link_to (@current_count.to_s+"/"+@total_count.to_s).html_safe, rota_slot_admin_schedules_path(@thedate,@number), :remote => true %>&nbsp;</span>
</td>

app/views/admin/schedules/destroy.js.erb
$('#<%=@element_id%>').html("<%=escape_javascript(render :partial=>'book')%>").addClass("bookable").removeClass("booked");
$('#<%=@element_id%>').find(".bookable_span").click(function(){
  $(this).find("form").submit();
});

app/views/admin/schedules/index.html.erb
<% content_for :menu do %>
  <ul class='maintabmenu'><li class='current'><a href='javascript:void(0)'>Schedule</a></li></ul>
<% end %>
<table style="width:100%" class="fc-header">
  <tbody>
    <tr>
      <td class="fc-header-left">
        <span class="fc-button-content">&nbsp;</span>
      </td>
      <td class="fc-header-center">
        <span class="schedule-week-during">
          <% thedate = @thedate.beginning_of_week 
             weekenddate = @thedate.end_of_week  %>
          <h2><%= thedate.strftime("%b %e"); %>  &mdash; <%= weekenddate.strftime("%b %e %Y"); %></h2>
        </span>
      </td>
      <td class="fc-header-right">
        <span class="schedule-week-today fc-button"><%= link_to "today", admin_schedules_url %></span>
        <span class="schedule-week-previous fc-button">
          <%=link_to "«", index_by_date_admin_schedules_path(thedate-1) %>
        </span>
        <span class="schedule-week-next fc-button">
          <%=link_to "»", index_by_date_admin_schedules_path(thedate+8) %>
        </span>  
      </td>
    </tr>
  </tbody>
</table>
<div class="schedule_management">
  <table class="stdtable" border="0" cellpadding="0" cellspacing="0">
    <colgroup>
      <col class="con0">
      <col class="con1">
      <col class="con0">
      <col class="con1">
      <col class="con0">
    </colgroup>
    <thead>
      <tr>
        <th class="head0">Week</th>
        <% (0..11).each do | d | %>
          <th class="head1"><%= d*2 %></th>
          <th class="head0"><%= d*2+1 %></th>
        <% end %>  
      </tr>
    </thead>
    <tbody>
      <%  (0..6).each do |w| %>
        <% day_shedules = @schedules[w] %>
          <tr>
            <td><%= (thedate+w).strftime("%a, %d/%m") %> </td>
            <% (0..23).each do |num| %>
              <% s = is_bookable(@schedules[w][num], thedate+w, num) %>
              <td class="<%= s %>" id="td_<%=  (w.to_s+"_"+num.to_s) %>">
                <%  case s
                when "bookable"
                  title = "title = Book" %>
                  <%= render "book", :new_schedule=>@op_schedules[w][num],:id=>("td_"+w.to_s+"_"+num.to_s) %>
                <%  
                when "booked" 
                  title = "title = Cancel" %>
                    <%= render "cancel", :schedule=>@op_schedules[w][num],:id=>("td_"+w.to_s+"_"+num.to_s) %>
                <% else
                  title = "" %>
                  <span class="<%= s %>_span" <%= title  %> ><%= s.html_safe  %>&nbsp;</span>
                <%  end %>
              </td>
            <% end %>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div>
  <%= form_tag request_holidays_admin_schedules_path, {:class=>"stdform requests-holiday"}  do %>
    <label class="request-holiday">
      From
    </label>
    <input class="date-pick" name="start_date">
    <label class="request-holiday">
      To
    </label>
    <input class="date-pick" name="end_date">
    <select class="request-holiday" name="setting">
      <option value="set">Set</option>
      <option value="unset">Unset</option>
    </select>
    <input type="submit" value="Request Holidays" class="request-holiday">
  <% end %>
</div>  
<%= link_to "<span>GoTo Work page</span>".html_safe, work_page_admin_schedules_path, :class=>"anchorbutton goto_workpage"  %>  

app/views/admin/schedules/note.js.erb
$('.note_history').html("<%=escape_javascript(render :partial=>'note_history')%>");

app/views/admin/schedules/rota_index.html.erb
<% content_for :menu do %>
  <ul class='maintabmenu'><li class='current'><a href='javascript:void(0)'>Rota</a></li></ul>
<% end %>
<table style="width:100%" class="fc-header">
  <tbody>
    <tr>
      <td class="fc-header-left">
        <span class="fc-button-content">&nbsp;</span>
      </td>
      <td class="fc-header-center">
        <span class="schedule-week-during">
          <% thedate = @thedate.beginning_of_week 
             weekenddate = @thedate.end_of_week  %>
          <h2><%= thedate.strftime("%b %e"); %>  &mdash; <%= weekenddate.strftime("%b %e %Y"); %></h2>
        </span>
      </td>
      <td class="fc-header-right">
        <span class="schedule-week-today fc-button"><%= link_to "today", admin_schedules_url %></span>
        <span class="schedule-week-previous fc-button">
          <%=link_to "«", rindex_by_date_admin_schedules_path(thedate-7) %>
        </span>
        <span class="schedule-week-next fc-button">
          <%=link_to "»", rindex_by_date_admin_schedules_path(thedate+7) %>
        </span>  
      </td>
    </tr>
  </tbody>
</table>
<div class="schedule_management">
  <table class="stdtable" border="0" cellpadding="0" cellspacing="0">
    <colgroup>
      <col class="con0">
      <col class="con1">
      <col class="con0">
      <col class="con1">
      <col class="con0">
    </colgroup>
    <thead>
      <tr>
        <th class="head0">Week</th>
        <th class="head1">0</th>
        <th class="head0">1</th>
        <th class="head1">2</th>
        <th class="head0">3</th>
        <th class="head1">4</th>
        <th class="head0">5</th>
        <th class="head1">6</th>
        <th class="head0">7</th>
        <th class="head1">8</th>
        <th class="head0">9</th>
        <th class="head1">10</th>
        <th class="head0">11</th>
        <th class="head1">12</th>
        <th class="head0">13</th>
        <th class="head1">14</th>
        <th class="head0">15</th>
        <th class="head1">16</th>
        <th class="head0">17</th>
        <th class="head1">18</th>
        <th class="head0">19</th>
        <th class="head1">20</th>
        <th class="head0">21</th>
        <th class="head1">22</th>
        <th class="head0">23</th>
      </tr>
    </thead>
    <tbody>
      <%  (0..6).each do |w| %>
        <% day_shedules = @schedules[w] %>
          <tr>
            <td><%= (thedate+w).strftime("%a, %d/%m") %> </td>
            <% (0..23).each do |num| %>
              <% 
                s=""
                if @schedules[w][num][:count]>0
                  s = "full_fill"
                  if @schedules[w][num][:total_count] > @schedules[w][num][:count]
                    s = "full_not"
                  end
                end
              %>
              <td class="<%= s %>" id="td_<%=  (w.to_s+"_"+num.to_s) %>">
                <span class="<%= s %>_span" ><%= link_to (@schedules[w][num][:count].to_s+"/"+@schedules[w][num][:total_count].to_s).html_safe, rota_slot_admin_schedules_path(thedate+w,num), :remote => true %>&nbsp;</span>
              </td>
            <% end %>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>  
<div id="rota_slot">  
  <%= render "rota_details_per_slot" %>
</div>    
<script>
  //<![CDATA[
  var operators = [<% 
    @operators.each do |operator| %>
      "<%=  operator.name %>",
    <%  end %>];
  //]]>
</script>  